-- MySQL Script generated by MySQL Workbench
-- Do 19 Mär 2020 12:59:05 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nachbarshilfe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nachbarshilfe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nachbarshilfe` DEFAULT CHARACTER SET utf8 ;
USE `nachbarshilfe` ;

-- -----------------------------------------------------
-- Table `nachbarshilfe`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nachbarshilfe`.`users` ;

CREATE TABLE IF NOT EXISTS `nachbarshilfe`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `adress` MEDIUMTEXT NULL,
  `plz` TINYTEXT NOT NULL,
  `email` TINYTEXT NULL,
  `phone` TINYTEXT NULL,
  `password` VARCHAR(45) NOT NULL,
  `last_updated` VARCHAR(45) NOT NULL,
  `login_timestamp` VARCHAR(45) NULL,
  `valid` TINYINT(1) NOT NULL DEFAULT -1,
  `role` VARCHAR(45) NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nachbarshilfe`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nachbarshilfe`.`requests` ;

CREATE TABLE IF NOT EXISTS `nachbarshilfe`.`requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT UNSIGNED NOT NULL,
  `last_updated` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  `text` LONGTEXT NULL,
  PRIMARY KEY (`id`, `user`),
  INDEX `fk_requests_users1_idx` (`user` ASC),
  CONSTRAINT `fk_requests_users1`
    FOREIGN KEY (`user`)
    REFERENCES `nachbarshilfe`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nachbarshilfe`.`offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nachbarshilfe`.`offers` ;

CREATE TABLE IF NOT EXISTS `nachbarshilfe`.`offers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT UNSIGNED NOT NULL,
  `last_updated` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  `text` LONGTEXT NULL,
  PRIMARY KEY (`id`, `user`),
  INDEX `fk_offers_users_idx` (`user` ASC),
  CONSTRAINT `fk_offers_users`
    FOREIGN KEY (`user`)
    REFERENCES `nachbarshilfe`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nachbarshilfe`.`supplies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nachbarshilfe`.`supplies` ;

CREATE TABLE IF NOT EXISTS `nachbarshilfe`.`supplies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `offer` INT UNSIGNED NOT NULL,
  `user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `offer`, `user`),
  INDEX `fk_offers_has_users_users1_idx` (`user` ASC),
  INDEX `fk_offers_has_users_offers1_idx` (`offer` ASC, `id` ASC),
  CONSTRAINT `fk_offers_has_users_offers1`
    FOREIGN KEY (`offer` , `id`)
    REFERENCES `nachbarshilfe`.`offers` (`id` , `user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offers_has_users_users1`
    FOREIGN KEY (`user`)
    REFERENCES `nachbarshilfe`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
